[colors.bright]
black = "0x4D4D4D"
blue = "0xCAA9FA"
cyan = "0x9AEDFE"
green = "0x5AF78E"
magenta = "0xFF92D0"
red = "0xFF6E67"
white = "0xE6E6E6"
yellow = "0xF1FA8C"

[colors.dim]
black = "0x4D4D4D"
blue = "0xCAA9FA"
cyan = "0x9AEDFE"
green = "0x5AF78E"
magenta = "0xFF92D0"
red = "0xFF6E67"
white = "0xE6E6E6"
yellow = "0xF1FA8C"

[colors.normal]
black = "0x282A36"
blue = "0xBD93F9"
cyan = "0x8BE9FD"
green = "0x50FA7B"
magenta = "0xFF79C6"
red = "0xFF5555"
white = "0x828791"
yellow = "0xF1FA8C"

[colors.primary]
background = "0x282A36"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"

[font]
size = 14.0

[font.normal]
family = "Monospace"
style = "Regular"

[window]
dynamic_title = true

[window.padding]
x = 8
y = 8
