#!/usr/bin/env bash

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

xrdb merge $HOME/.Xresources

screenlayout.sh &

pkill volumeicon
volumeicon &

pkill nm-applet
nm-applet &

pkill sxhkd
sxhkd &

pkill nitrogen
nitrogen --restore &

