#!/usr/bin/env bash

xrdb merge $HOME/.Xresources

# pkill volumeicon
# volumeicon &

# pkill nm-applet
# nm-applet &

pkill sxhkd
sxhkd &

# pkill nitrogen
# nitrogen --restore &

pkill urxvtd
urxvtd &
