#!/bin/bash



OPT=$(echo -e "Lock\nExit\nSuspend\nReboot\nShutdown" | dmenu -i -p "Select an option ")

# Performs exit options
case "$OPT" in
    Lock)
        ./blurlock
        ;;
    Exit)
        i3-msg exit
        ;;
    Suspend)
        i3-blurlock && systemctl suspend
        ;;
    Reboot)
        reboot
        ;;
    Shutdown)
        poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac
exit 0

