#!/bin/sh

# find all files in dotfiles directory, but exclude .git

git_dot() {
  git --git-dir=$HOME/.dot/ --work-tree=$HOME ls-tree --name-only -r HEAD
}

FILE=$( git_dot | dmenu -i -p "Edit dotfiles")

# -n STRING => STRING lenght is > 0
if [ -n "$FILE" ]
then
    exec "$TERMINAL" -e "$EDITOR" "$FILE"
    exit 0
else
    echo "false"
    exit 1
fi
