#!/bin/sh

# find all files in dotfiles directory, but exclude .git
FILE=$(find "$HOME"/dotfiles "$HOME"/.local/suckless -type f -not -path '*/\.git/*'| dmenu -i -l 10 -p "Edit dotfiles")

# -n STRING => STRING lenght is > 0
if [ -n "$FILE" ]
then
    exec "$TERMINAL" -e "$EDITOR" "$FILE"
    exit 0
else
    echo "false"
    exit 1
fi
