#!/bin/sh

# find all files in dotfiles directory, but exclude .git
FILE=$(find ~/dotfiles ~/.local/suckless -type f -not -path '*/\.git/*' | fzy -p "Choose a file: ")

# -n STRING => STRING lenght is > 0
if [ -n $FILE ]
then
    exec $EDITOR $FILE
    exit 0
else
    exit 1
fi
