#!/bin/bash

# find all files in dotfiles directory, but exclude .git
script=$(echo -e "$(find $HOME/dotfiles -type f -not -path '*/\.git/*')" | fzy)

# -n STRING => STRING lenght is > 0
#if [ -z $script ]
if [ ! -z $script ]
then
    exec $EDITOR $script
    exit 0
else
    exit 1
fi
