#!/usr/bin/env bash

# Terminate already running bar instances
killall -q compton

while pgrep -u $UID -x compton >/dev/null; do sleep 1; done

echo "---" | tee -a /tmp/compton.log
compton --blur-background -b >> /tmp/compton.log 2>&1 &

