#!/bin/bash

options=("bash
i3
i3blocks
termite
tmux
sxhkd
Xresources
profile
polybar
xinputrc
xinitrc
zsh
")

choice=$(echo -e "${options[@]}" | dmenu -i -p 'Edit a config file: ')

case "$choice" in
    bash)
        exec st -e $EDITOR ~/.bashrc
        ;;
    i3)
        exec urxvt -e $EDITOR ~/.config/i3/config
        ;;
    i3blocks)
        exec termite -e $EDITOR ~/.config/i3/i3blocks.conf
        ;;
    termite)
        exec $TERMINAL -e $EDITOR ~/.config/termite/config
        ;;
    tmux)
        exec $TERMINAL -e $EDITOR ~/.tmux.conf
        ;;
    sxhkd)
        exec $TERMINAL -e $EDITOR ~/.config/sxhkd/sxhkdrc
        ;;
    Xresources)
        exec $TERMINAL -e $EDITOR ~/.Xresources
        ;;
    profile)
        exec $TERMINAL -e $EDITOR ~/.profile
        ;;
    polybar)
        exec $TERMINAL -e $EDITOR ~/.config/polybar/config
        ;;
    xinputrc)
        exec $TERMINAL -e $EDITOR ~/.xinputrc
        ;;
    xinitrc)
        exec $TERMINAL -e $EDITOR ~/.xinitrc
        ;;
    zsh)
        exec $TERMINAL -e $EDITOR ~/.zshrc
        ;;
esac
exit 0
