#!/bin/bash

options=("bash
compton
i3
i3blocks
polybar
profile
spacemacs
st
sxhkd
termite
tmux
xinitrc
xinputrc
Xresources
zsh
")

choice=$(echo -e "${options[@]}" | dmenu -i -p 'Edit a config file: ')

case "$choice" in
    bash)
        exec emacsclient -nc ~/.bashrc
        ;;
    compton)
        exec emacsclient -nc ~/.config/compton.conf
        ;;
    i3)
        exec emacsclient -nc ~/.config/i3/config
        ;;
    i3blocks)
        exec emacsclient -nc ~/.config/i3/i3blocks.conf
        ;;
    polybar)
        exec emacsclient -nc ~/.config/polybar/config
        ;;
    profile)
        exec emacsclient -nc ~/.profile
        ;;
    spacemacs)
        exec emacsclient -nc ~/.spacemacs
        ;;
    st)
        exec emacsclient -nc ~/bin/st/config.h
        ;;
    sxhkd)
        exec emacsclient -nc  ~/.config/sxhkd/sxhkdrc
        ;;
    termite)
        exec emacsclient -nc ~/.config/termite/config
        ;;
    tmux)
        exec emacsclient -nc ~/.tmux.conf
        ;;
    xinitrc)
        exec emacsclient -nc ~/.xinitrc
        ;;
    xinputrc)
        exec emacsclient -nc ~/.xinputrc
        ;;
    Xresources)
        exec emacsclient -nc ~/.Xresources
        ;;
    zsh)
        exec emacsclient -nc ~/.zshrc
        ;;
esac
exit 0
