#!/bin/bash

script=$(echo -e "$(ls ~/.scripts)" | dmenu -i -p "Select a script to edit")

echo $script
# -n STRING => STRING lenght is > 0
#if [ -z $script ]
if [ ! -z $script ]
then
    # exec $TERMINAL -e emacsclient -nc ~/.scripts/$script
    exec emacsclient ~/.scripts/$script
    exit 0
else
    echo "false"
    exit 1
fi
