#!/bin/env bash

options=("bash
compton
i3
i3blocks
polybar
profile
spacemacs
st
sxhkd
termite
tmux
initrc
xinputrc
Xresources
zsh
")

choice=$(echo -e "${options[@]}" | dmenu -i -p 'Edit a config file: ')

case "$choice" in
    bash)
        exec $TERMINAL -e $EDITOR ~/.bashrc
        ;;
    compton)
        exec $TERMINAL -e $EDITOR ~/.config/compton.conf
        ;;
    i3)
        exec $TERMINAL -e $EDITOR ~/.config/i3/config
        ;;
    i3blocks)
        exec $TERMINAL -e $EDITOR ~/.config/i3/i3blocks.conf
        ;;
    inputrc)
        exec $TERMINAL -e $EDITOR ~/.inputrc
        ;;
    polybar)
        exec $TERMINAL -e $EDITOR ~/.config/polybar/config
        ;;
    profile)
        exec $TERMINAL -e $EDITOR ~/.profile
        ;;
    spacemacs)
        exec $TERMINAL -e $EDITOR ~/.spacemacs
        ;;
    st)
        exec $TERMINAL -e $EDITOR ~/bin/st/config.h
        ;;
    sxhkd)
        exec $TERMINAL -e $EDITOR  ~/.config/sxhkd/sxhkdrc
        ;;
    termite)
        exec $TERMINAL -e $EDITOR ~/.config/termite/config
        ;;
    tmux)
        exec $TERMINAL -e $EDITOR ~/.tmux.conf
        ;;
    xinitrc)
        exec $TERMINAL -e $EDITOR ~/.xinitrc
        ;;
    Xresources)
        exec $TERMINAL -e $EDITOR ~/.Xresources
        ;;
    zsh)
        exec $TERMINAL -e $EDITOR ~/.zshrc
        ;;
esac
exit 0
