#!/bin/bash

OPT=$(echo -e "Lock\nExit\nSuspend\nReboot" | dmenu -i -p "Select an option:")

# Performs exit options
case "$OPT" in
    Lock)
        blurlock
        ;;
    Exit)
        i3-msg exit
        ;;
    Suspend)
        blurlock && systemctl suspend
        ;;
    Reboot)
        reboot
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac
exit 0

