# Misc
alias rbash='source ~/.bashrc'
alias rn='ranger'
alias scripts='cd ~/.scripts'
# apt-get
alias sa='sudo apt'
alias sag='sudo apt-get'
alias agsearch='apt-cache search'
alias aginstall='sudo apt-get install'
alias agremove='sudo apt-get remove --purge'
# Pacman
alias p='pacman'
alias sp='sudo pacman'
alias pac='pacman'
alias spac='sudo pacman'
alias pacs='pacman -Ss'
alias paci='sudo pacman -S'
alias pacup='sudo pacman -Syu'
alias pacrm='sudo pacman -Rus'
# Navigation
alias ll='ls -lsA'
alias la='ls -A'
alias l='ls -CF'
alias dotfiles='cd ~/dotfiles'
# vim & neovim
alias vim='nvim'
alias v='vim'
alias valias='vim ~/.bash_aliases'
alias vprofile='vim ~/.profile'
# cd to projects folder
alias nextapi='cd ~/Projects/ICS.NextMobile/ICS.NextMobile.API'
alias nextadmin='cd ~/Projects/ICS.NextMobile/ICS.NextMobile.Admin'
alias nextapproval='cd ~/Projects/ICS.NextMobile/ICS.NextMobile.ApprovalTrip'
alias nextchef='cd ~/Projects/ICS.NextMobile/ICS.NextMobile.Chef'
alias proj='cd ~/Projects'
